images:
  controlPlane:
    - name: ubuntu-capi-image-v1.27.5
  worker:
    - name: ubuntu-capi-image-v1.27.5
externalNetworkId: ebfe5546-f09f-4f42-ab54-094e457d42e
dnsNameservers: 
  - 62.138.222.111 
  - 62.138.222.222
controlPlaneFlavor: SCS-2V:4:20
workerFlavor: SCS-2V:4:20