apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}-control-plane
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              cloud-provider: external
          controllerManager:
            extraArgs:
              cloud-provider: external
          dns:
            imageRepository: registry.k8s.io/coredns
          etcd:
            local:
              dataDir: /var/lib/etcd
              extraArgs:
                auto-compaction-mode: periodic
                auto-compaction-retention: 8h
                election-timeout: "2500"
                heartbeat-interval: "250"
                snapshot-count: "6400"
          imageRepository: registry.k8s.io
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
              provider-id: openstack:///'{{"{{"}}instance_id{{"}}"}}'
            name: '{{"{{"}}local_hostname{{"}}"}}'
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
              provider-id: openstack:///'{{"{{"}}instance_id{{"}}"}}'
            name: '{{"{{"}}local_hostname{{"}}"}}'
        files: {{ if .Values.etcd_defrag }}
          - content: |
{{ .Files.Get "files/etcd-defrag.sh" | indent 14 }} 
            owner: root:root
            path: /root/etcd-defrag.sh
            permissions: "0755"
          - content: |
{{ .Files.Get "files/etcd-defrag.service" | indent 14 }} 
            owner: root:root
            path: /etc/systemd/system/etcd-defrag.service
            permissions: "0644"
          - content: |
{{ .Files.Get "files/etcd-defrag.timer" | indent 14 }} 
            owner: root:root
            path: /etc/systemd/system/etcd-defrag.timer
            permissions: "0644"
        {{ end }}
        postKubeadmCommands:
        preKubeadmCommands:
