apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackClusterTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}-cluster
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      cloudName: gx-scs
      identityRef:
        name: cs-cluster-cloud-config
        kind: Secret
      apiServerLoadBalancer:
        enabled: true
      managedSecurityGroups: true
      nodeCidr: 10.8.0.0/20
      dnsNameservers: {{ .Values.dnsNameservers }}
      externalNetworkId: {{ .Values.externalNetworkId }}
